server:
  port: 11451

student: 
    number: 20200
    name: Putin
    gender: male
    age: 999

teacher: 
    number: 2013
    name: Zelensky
    age: 999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mackenia.xyz:3306/springboot
    username: sql
    password: mysql
  thymeleaf:
    cache: false
