server:
  port: 11451

spring:
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mackenia.xyz:3306/springboot
    username: sql
    password: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations:
        - classpath:resources/static
        - classpath:file:${photo.file.dir}

  redis:
    host: cqnu.mackenia.xyz
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-wait: 10000
        max-idle: 10
        min-idle: 1
    password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

photo:
  file:
    dir: resources/static/photo