server:
  port: 11451

student: 
    number: 20200
    name: Putin
    gender: male
    age: ???
    grade: one

teacher: 
    number: 2013
    name: Zelensky
    age: ???
    position: senior
    wage: 10k


