server:
  port: 11451

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mackenia.xyz:3306/springboot
    username: sql
    password: mysql
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  rabbitmq:
    host: luketebo.top
    port: 5672
    username: admin
    password: admin
  mail:
    host: smtp.exmail.qq.com
    port: 465
    
    username: 2020051615308@stu.cqnu.edu.cn
    password: 
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

